package eSPIMdeskew_v2;

import org.micromanager.PropertyMap;
import org.micromanager.Studio;
import org.micromanager.data.ProcessorConfigurator;
/**
 *
 * @author Yina
 */
public class DeskewConfigurator extends javax.swing.JFrame implements ProcessorConfigurator{
    
    private Studio studio_;
    public boolean updateFlag;
    /**
     * Creates new form NewJFrame
     */
    public DeskewConfigurator() {
        initComponents();
    }
     public DeskewConfigurator(Studio studio, PropertyMap settings) {
        initComponents();
        studio_=studio;
        updateFlag = false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_zstep = new javax.swing.JTextField();
        jLabel_zstep = new javax.swing.JLabel();
        jLabel_zstepunit = new javax.swing.JLabel();
        jLabel_Pixelsize = new javax.swing.JLabel();
        jTextField_Pixelsize = new javax.swing.JTextField();
        jLabel_Pixelsizeunit = new javax.swing.JLabel();
        jLabel_Angle = new javax.swing.JLabel();
        jTextField_Angle = new javax.swing.JTextField();
        jLabel_angleunit = new javax.swing.JLabel();
        jLabel_timepoint = new javax.swing.JLabel();
        jTextField_interval = new javax.swing.JTextField();
        jCheckBox_saveDeskewFile = new javax.swing.JCheckBox();
        jCheckBox_motionCorrection = new javax.swing.JCheckBox();
        jLabel_zstep1 = new javax.swing.JLabel();
        jTextField_posNumXY = new javax.swing.JTextField();
        jLabel_zstep2 = new javax.swing.JLabel();
        jTextField_posNumZ = new javax.swing.JTextField();
        jLabel_zstep3 = new javax.swing.JLabel();
        jLabel_zstep4 = new javax.swing.JLabel();
        jTextField_XYStage = new javax.swing.JTextField();
        jTextField_ZStage = new javax.swing.JTextField();
        jLabel_zstep5 = new javax.swing.JLabel();
        jTextField_basedChannel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_zstep.setText("0.8");
        jTextField_zstep.setToolTipText("");
        jTextField_zstep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_zstepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_zstepMouseExited(evt);
            }
        });
        jTextField_zstep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_zstepActionPerformed(evt);
            }
        });

        jLabel_zstep.setText("z_step");

        jLabel_zstepunit.setText("(um)");

        jLabel_Pixelsize.setText("Pixelsize");

        jTextField_Pixelsize.setText("133");
        jTextField_Pixelsize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_PixelsizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_PixelsizeMouseExited(evt);
            }
        });

        jLabel_Pixelsizeunit.setText("(nm)");

        jLabel_Angle.setText("Lightsheet angle");

        jTextField_Angle.setText("30");
        jTextField_Angle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_AngleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_AngleMouseExited(evt);
            }
        });

        jLabel_angleunit.setText("(degree)");

        jLabel_timepoint.setText("Volume interval to process:");

        jTextField_interval.setText("1");
        jTextField_interval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_intervalActionPerformed(evt);
            }
        });

        jCheckBox_saveDeskewFile.setSelected(true);
        jCheckBox_saveDeskewFile.setText("Save deskew file");
        jCheckBox_saveDeskewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_saveDeskewFileActionPerformed(evt);
            }
        });

        jCheckBox_motionCorrection.setSelected(true);
        jCheckBox_motionCorrection.setText("Enable motion correction");
        jCheckBox_motionCorrection.setActionCommand("MotionCorrection");

        jLabel_zstep1.setText("XY Position Number");

        jTextField_posNumXY.setText("3");
        jTextField_posNumXY.setToolTipText("");
        jTextField_posNumXY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_posNumXYMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_posNumXYMouseExited(evt);
            }
        });
        jTextField_posNumXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_posNumXYActionPerformed(evt);
            }
        });

        jLabel_zstep2.setText("Slices per XY");

        jTextField_posNumZ.setText("1");
        jTextField_posNumZ.setToolTipText("");
        jTextField_posNumZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_posNumZMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_posNumZMouseExited(evt);
            }
        });
        jTextField_posNumZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_posNumZActionPerformed(evt);
            }
        });

        jLabel_zstep3.setText("Position XY Stage");

        jLabel_zstep4.setText("Position Z  Stage");

        jTextField_XYStage.setText("XYStage");
        jTextField_XYStage.setToolTipText("");
        jTextField_XYStage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_XYStageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_XYStageMouseExited(evt);
            }
        });
        jTextField_XYStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_XYStageActionPerformed(evt);
            }
        });

        jTextField_ZStage.setText("TIZDrive");
        jTextField_ZStage.setToolTipText("");
        jTextField_ZStage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_ZStageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_ZStageMouseExited(evt);
            }
        });
        jTextField_ZStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ZStageActionPerformed(evt);
            }
        });

        jLabel_zstep5.setText("Based channel");

        jTextField_basedChannel.setText("0");
        jTextField_basedChannel.setToolTipText("");
        jTextField_basedChannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_basedChannelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_basedChannelMouseExited(evt);
            }
        });
        jTextField_basedChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_basedChannelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Angle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel_zstep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_zstep, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_Angle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_Pixelsize)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Pixelsize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_zstepunit)
                    .addComponent(jLabel_Pixelsizeunit)
                    .addComponent(jLabel_angleunit))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_motionCorrection)
                    .addComponent(jCheckBox_saveDeskewFile)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_timepoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_interval, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_zstep4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_ZStage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_zstep3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_XYStage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_zstep1)
                                .addComponent(jLabel_zstep2)
                                .addComponent(jLabel_zstep5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_posNumZ, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_posNumXY, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_basedChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_zstep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_zstep, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Pixelsize)
                            .addComponent(jTextField_Pixelsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Pixelsizeunit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Angle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_angleunit)))
                    .addComponent(jLabel_zstepunit))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_saveDeskewFile)
                .addGap(34, 34, 34)
                .addComponent(jCheckBox_motionCorrection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_zstep1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_posNumXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_zstep2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_posNumZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_basedChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_zstep5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_zstep3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_XYStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_zstep4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ZStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_timepoint)
                    .addComponent(jTextField_interval, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jCheckBox_motionCorrection.getAccessibleContext().setAccessibleName("MotionCorrection");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_zstepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_zstepMouseEntered
        if(studio_.acquisitions().isAcquisitionRunning()){
            jTextField_zstep.disable();
        }
    }//GEN-LAST:event_jTextField_zstepMouseEntered

    private void jTextField_zstepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_zstepMouseExited
        jTextField_zstep.enable();
    }//GEN-LAST:event_jTextField_zstepMouseExited

    private void jTextField_PixelsizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_PixelsizeMouseEntered
        if(studio_.acquisitions().isAcquisitionRunning()){
            jTextField_Pixelsize.disable();
        }
    }//GEN-LAST:event_jTextField_PixelsizeMouseEntered

    private void jTextField_PixelsizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_PixelsizeMouseExited
        jTextField_Pixelsize.enable();
    }//GEN-LAST:event_jTextField_PixelsizeMouseExited

    private void jTextField_AngleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_AngleMouseEntered
        if(studio_.acquisitions().isAcquisitionRunning()){
            jTextField_Angle.disable();
            jTextField_Angle.setToolTipText("Editting disabled during acquisition!");
        }
    }//GEN-LAST:event_jTextField_AngleMouseEntered

    private void jTextField_AngleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_AngleMouseExited
        jTextField_Angle.enable();
    }//GEN-LAST:event_jTextField_AngleMouseExited

    private void jCheckBox_saveDeskewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_saveDeskewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_saveDeskewFileActionPerformed

    private void jTextField_posNumXYMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_posNumXYMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posNumXYMouseEntered

    private void jTextField_posNumXYMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_posNumXYMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posNumXYMouseExited

    private void jTextField_posNumXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_posNumXYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posNumXYActionPerformed

    private void jTextField_posNumZMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_posNumZMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posNumZMouseEntered

    private void jTextField_posNumZMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_posNumZMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posNumZMouseExited

    private void jTextField_posNumZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_posNumZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_posNumZActionPerformed

    private void jTextField_intervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_intervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_intervalActionPerformed

    private void jTextField_XYStageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_XYStageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_XYStageMouseEntered

    private void jTextField_XYStageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_XYStageMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_XYStageMouseExited

    private void jTextField_XYStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_XYStageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_XYStageActionPerformed

    private void jTextField_ZStageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ZStageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ZStageMouseEntered

    private void jTextField_ZStageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ZStageMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ZStageMouseExited

    private void jTextField_ZStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ZStageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ZStageActionPerformed

    private void jTextField_basedChannelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_basedChannelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_basedChannelMouseEntered

    private void jTextField_basedChannelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_basedChannelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_basedChannelMouseExited

    private void jTextField_basedChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_basedChannelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_basedChannelActionPerformed

    private void jTextField_zstepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_zstepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_zstepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeskewConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeskewConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeskewConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeskewConfigurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeskewConfigurator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_motionCorrection;
    private javax.swing.JCheckBox jCheckBox_saveDeskewFile;
    private javax.swing.JLabel jLabel_Angle;
    private javax.swing.JLabel jLabel_Pixelsize;
    private javax.swing.JLabel jLabel_Pixelsizeunit;
    private javax.swing.JLabel jLabel_angleunit;
    private javax.swing.JLabel jLabel_timepoint;
    private javax.swing.JLabel jLabel_zstep;
    private javax.swing.JLabel jLabel_zstep1;
    private javax.swing.JLabel jLabel_zstep2;
    private javax.swing.JLabel jLabel_zstep3;
    private javax.swing.JLabel jLabel_zstep4;
    private javax.swing.JLabel jLabel_zstep5;
    private javax.swing.JLabel jLabel_zstepunit;
    private javax.swing.JTextField jTextField_Angle;
    private javax.swing.JTextField jTextField_Pixelsize;
    private javax.swing.JTextField jTextField_XYStage;
    private javax.swing.JTextField jTextField_ZStage;
    private javax.swing.JTextField jTextField_basedChannel;
    private javax.swing.JTextField jTextField_interval;
    private javax.swing.JTextField jTextField_posNumXY;
    private javax.swing.JTextField jTextField_posNumZ;
    private javax.swing.JTextField jTextField_zstep;
    // End of variables declaration//GEN-END:variables

    public double getZstep() {
      return (double) Double.parseDouble(jTextField_zstep.getText());
    }
    
    public double getAngle() {
      return (double) Double.parseDouble(jTextField_Angle.getText());
    }
    
    public int getPixelsize() {
      return (int) Integer.parseInt(jTextField_Pixelsize.getText());
    }
    
    public int getVolumeinterval() {
      return (int) Integer.parseInt(jTextField_interval.getText());
    }
    public int getPosNumXY() {
      return (int) Integer.parseInt(jTextField_posNumXY.getText());
    }
    public int getPosNumZ() {
      return (int) Integer.parseInt(jTextField_posNumZ.getText());
    }
    public int getBasedChannel() {
      return (int) Integer.parseInt(jTextField_basedChannel.getText());
    }
    
    public String getXYStageName(){
        return jTextField_XYStage.getText();
    }
    
    public String getZStageName(){
        return jTextField_ZStage.getText();
    }
    
    public boolean getSaveFileCheckbox(){
        return (boolean) jCheckBox_saveDeskewFile.isSelected();
    }
    public boolean getMotionCorrectionCheckbox(){
        return (boolean) jCheckBox_motionCorrection.isSelected();
    }
    

    
    @Override
    public void showGUI() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("eSPIM deskew");
        
        setVisible(true);
    }

    @Override
    public void cleanup() {   
    }

    @Override
    public PropertyMap getSettings() { 
        PropertyMap.PropertyMapBuilder builder = studio_.data().getPropertyMapBuilder();
        return builder.build();
    }
}
